# Generated by Django 2.2.5 on 2019-09-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VulCNNVD',
            new_name='CNNVD',
        ),
        migrations.RenameModel(
            old_name='VulPaper',
            new_name='News',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-updated'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
